name: enumerator_workspace

environment:
  sdk: ^3.10.8

workspace:
  - packages/enumerator_annotation
  - packages/enumerator_builder
  - packages/enumerator_annotation/example

dev_dependencies:
  melos: ^7.4.0
  very_good_analysis: ^10.0.0

melos:
  repository: https://github.com/albinpk/dart_enumerator
  sdkPath: .fvm/flutter_sdk
  scripts:
    clean: melos exec -c 1 "fvm dart run build_runner clean && fvm flutter clean"
