name: example
description: Enumerators example
version: 0.0.1-dev.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  enumerator_annotation:
    path: ../

dev_dependencies:
  build_runner: ^2.10.5
  enumerator_builder:
    path: ../../enumerator_builder
