name: enumerator
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.10.8

dev_dependencies:
  test: ^1.25.6
