name: enumerator_builder
description: Code generation utilities for Dart enums
version: 0.0.1-dev.0

homepage: https://github.com/albinpk/dart_enumerator
repository: https://github.com/albinpk/dart_enumerator
issue_tracker: https://github.com/albinpk/dart_enumerator/issues

resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  analyzer: ^10.0.2
  build: ^4.0.4
  built_collection: ^5.1.1
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  enumerator_annotation: ^0.0.1-dev.0
  source_gen: ^4.2.0

dev_dependencies:
  test: ^1.25.6
