name: enumerator_annotation
description: Code generation utilities for Dart enums
version: 0.0.1-dev.2

homepage: https://github.com/albinpk/dart_enumerator
repository: https://github.com/albinpk/dart_enumerator
issue_tracker: https://github.com/albinpk/dart_enumerator/issues

resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  collection: ^1.19.1
  meta: ^1.18.1

dev_dependencies:
  test: ^1.25.6

topics:
  - enum
  - extension
  - code-generation
  - enum-extension
  - enum-helper
